---
title: "Assignment9"
author: "Anthony"
date: "October 10, 2018"
output:
  word_document: default
  html_document: default
  word_documet: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 Dataset1 <- read.csv("C:/Users/student/Documents/MATH421/Dataset1 .csv")
```
#1
```{r}

Missing <- function(x) {
  return(sum(is.na(x)))
}
Missing(Dataset1)
```

#2
```{r}

MissingNames <- function(x) {
  return(names(which(colSums(is.na(x))>0)))
}
MissingNames(Dataset1)
```

#3
```{r}

SpecificMissingData <- function(x) {
  Columns <- names(which(colSums(is.na(x))>0))
  Numbers <- sapply(x, function(x) sum(is.na(x)))
  list(Columns, Numbers)
}
SpecificMissingData(Dataset1)
```
#4
```{r}
ReplaceData <- function(x) {
  for (i in 1:ncol(x)){
    if (is.numeric(x[,i])){
      x[,i][is.na(x[,i])]=mean(x[,i], na.rm=TRUE)
    }else{
      levels=unique(x[,i])
      x[,i][is.na(x[,i])]=levels[which.max(tabulate(match(x[,i], levels)))]
    }
  }
  return (head(x))
}
ReplaceData(Dataset1)
```

#5
```{r}
Q5 <- function(x){
  num_vars=c()
  cat_vars=c()
  for (i in 1:ncol(x)){
    if(is.numeric(x[,i])){
      num_vars=c(num_vars,names(x)[i])
    }else{
      cat_vars=c(cat_vars,names(x)[i])
    }
  }
  num_data=x[num_vars]
  cat_data=x[cat_vars]
  print(head(num_data))
  print(head(cat_data))
}
Q5(Dataset1)
```

#6
```{r}
library(ggplot2)

Q6 <- function(x){
  for (i in 1:ncol(x)){
    if (is.numeric(x[,i])){
      print(ggplot(data=x)+geom_density(mapping=aes(x=x[,i]))+xlab(names(x)[i]))
    }
  }
}
Q6(Dataset1)
```

#7
```{r}
Q7 <- function(x){
  for (i in 1:ncol(x)){
    if (!is.numeric(x[,i])){
      print(ggplot(data=x)+geom_bar(mapping=aes(x=x[,i]))+xlab(names(x)[i]))
    }
  }
}
Q7(Dataset1)
```

#8
```{r}
Q8 <- function(x,i,j){
    if(is.numeric(x[,i]) | is.numeric(x[,j])){
      print("not categorical variables")
    }else {
      print(ggplot(data=x)+geom_bar(mapping=aes(x=x[,i], fill=x[,j]),position = "dodge")+labs(x=names(x)[i],fill=names(x)[j]))
    }
  }

Q8(Dataset1,2,3)
Q8(Dataset1,1,3) 

```

#9
```{r}
Q9 <- function(x,i,j){
    if(!is.numeric(x[,i]) | !is.numeric(x[,j])){
      print("not numeric variables")
    }else {
      print(ggplot(data=x)+geom_point(mapping=aes(x=x[,i], y=x[,j]))+labs(x=names(x)[i],y=names(x)[j]))
    }
}

Q9(Dataset1,1,3)
Q9(Dataset1,1,2) 

```

#10
```{r}
Q10 <- function(x,i,j){
    if(!is.numeric(x[,i])){
      print("not numeric")
    }else if(is.numeric(x[,j])){
      print("not categorical")
    }else{
      print(ggplot(data=x)+geom_density(mapping = aes(x=x[,1],color=x[,j]))+labs(x=names(x)[i],color=names(x)[j]))
    }
}

Q10(Dataset1,1,2)
Q10(Dataset1,2,3) 
Q10(Dataset1,1,3)

```

#11
```{r}
Q11 <- function(x){
    for (i in 1:ncol(x)){
      if (!is.numeric(x[,i])){
        for(j in 1:ncol(x)){
          if (!is.numeric(x[,j]) & names(x)[j]!=names(x)[i]){
            print(ggplot(data=x)+geom_bar(mapping=aes(x=x[,i],fill=x[,j]),position="dodge")+ labs(x=names(x)[i],fill=names(x)[j]))
          }
        }
      }
    }
}
Q11(Dataset1)
```

#12
```{r}
Q12 <- function(x){
  for (i in 1:ncol(x)){
      if (!is.numeric(x[,i])){
        for(j in 1:ncol(x)){
          if (!is.numeric(x[,j]) & names(x)[j]!=names(x)[i]){
            print(ggplot(data=x)+geom_bar(mapping=aes(x=x[,i],fill=x[,j]),position="dodge")+ labs(x=names(x)[i],fill=names(x)[j]))
          }
        }
      }else{
        for(j in 1:ncol(x)){
          if (!is.numeric(x[,j])){
            print(ggplot(data=x)+geom_density(mapping=aes(x=x[,i],color=x[,j]))+labs(x=names(x)[i],color=names(x)[j]))
          }
        }
      }
  }
}
Q12(Dataset1)
```